[Advanced 2 fix:] Use bash to compile a Py script

diff --git a/0x00-python-hello_world/101-compile b/0x00-python-hello_world/101-compile
--- a/0x00-python-hello_world/101-compile
+++ b/0x00-python-hello_world/101-compile
@@ -2,13 +2,13 @@
 
 # Check for exported Python file
 if [ -z "$PYFILE" ]; then
-	echo "Missing environment variable PYFILE"
-	exit 1
+    echo "Missing environment variable PYFILE"
+    exit 1
 fi
 
 if [ ! -f "$PYFILE" ]; then
-	echo "File $PYFILE not found"
-	exit 1
+    echo "File $PYFILE not found"
+    exit 1
 fi
 
 # Compile the Python script
